[package]
name = "ff8_launcher"
version = "0.1.0"
edition = "2021"
authors = ["myst6re <myst6re@gmail.com>"]

[dependencies]
same-file = "1"
log = "0.4"
simplelog = "^0.12.2"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
