[package]
name = "moomba"
description = "Modern and fast FFNx configurator"
version = "0.1.0"
edition = "2021"
authors = ["myst6re <myst6re@gmail.com>"]
license = "GPL-3.0"
build = "build.rs"
default-run = "moomba"

[dependencies]
log = "0.4"
moomba_core = { path = "../core" }
slint = { version = "1.7", features = ["default", "raw-window-handle-06"] }
raw-window-handle = "0.6.0"
rfd = "0.14.1"
windows = {version = "0.56.0", features = ["Win32_UI_WindowsAndMessaging"]}

[build-dependencies]
slint-build = "1.5"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
