[package]
name = "mmb"
version = "0.1.0"
edition = "2021"
authors = ["myst6re <myst6re@gmail.com>"]

[dependencies]
moomba_core = { path = "../core" }
log = "0.4"
clap = "4"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
