[package]
name = "moomba_core"
version = "0.1.0"
edition = "2021"
authors = ["myst6re <myst6re@gmail.com>"]

[dependencies]
log = "0.4"
simplelog = "^0.12.2"
toml_edit = "0.22.9"
chrono = "0.4.37"
ureq = {version = "2.9.6", features = ["brotli"]}
zip = "0.6"
zip-extensions = "0.6"
directories = "5.0"
pelite = "=0.10.0"

[target.'cfg(windows)'.dependencies]
registry = "1.2"
utfx = "0.1"
windows = {version = "0.56.0", features = ["Win32_UI_Shell"]}
